DROP TABLE USER_TABLE;
DROP TABLE ROLE_TABLE;
DROP TABLE USER_ROLE_MAPPING;

CREATE TABLE ROLE_TABLE(
"ROLE_ID" NUMBER PRIMARY KEY,
"ROLE_NAME" VARCHAR2(255 CHAR),
"ACTIVE" CHAR(1 CHAR),
"LAST_UPDATED" TIMESTAMP (6),
"CREATED_ON" TIMESTAMP (6)
);

CREATE TABLE "USER_TABLE"
( "USER_ID" NUMBER(19,0) PRIMARY KEY,
"ACTIVE" CHAR(1 CHAR),
"CREATED_ON" TIMESTAMP (6),
"EMAIL_ID" VARCHAR2(255 CHAR),
"FIRST_NAME" VARCHAR2(255 CHAR),
"LAST_NAME" VARCHAR2(255 CHAR),
"LAST_UPDATED" TIMESTAMP (6),
"MOBILE" NUMBER(19,0),
"USER_PASSWORD" VARCHAR2(255 CHAR),
"USER_CODE" VARCHAR2(255 CHAR),
"USER_NAME" VARCHAR2(255 CHAR)
);

CREATE TABLE USER_ROLE_MAPPING(
"ID" NUMBER(19,0) PRIMARY KEY,
"USER_ID" NUMBER(19,0),
"ROLE_ID" NUMBER(19,0)
);

INSERT INTO ROLE_TABLE (ROLE_ID, ACTIVE, CREATED_ON, LAST_UPDATED, ROLE_NAME) VALUES(1, 'T',TO_DATE('2003/05/03 21:02:44', 'yyyy/mm/dd hh24:mi:ss'),
TO_DATE('2003/05/03 21:02:44', 'yyyy/mm/dd hh24:mi:ss'), 'RoleName');

INSERT INTO USER_TABLE ("USER_ID","ACTIVE", "CREATED_ON", "EMAIL_ID", "FIRST_NAME",
"LAST_NAME","LAST_UPDATED", "MOBILE","USER_PASSWORD", "USER_CODE", "USER_NAME") VALUES (1, 'T',TO_DATE('2003/05/03 21:02:44', 'yyyy/mm/dd hh24:mi:ss'),
'awef','AWEF','AWEF',TO_DATE('2003/05/03 21:02:44', 'yyyy/mm/dd hh24:mi:ss'),234234,'$2a$10$6UPpX7fslrQENHblFVuUGe0O8RBfDED.7Q3DgxjQP3WNujnkKxO1q',2,'samkuk');

--$2a$10$6UPpX7fslrQENHblFVuUGe0O8RBfDED.7Q3DgxjQP3WNujnkKxO1q is hash of aabbcc3#

INSERT INTO USER_ROLE_MAPPING (ID, USER_ID, ROLE_ID) VALUES (1, 1,1);

SELECT * FROM USER_TABLE;
SELECT * FROM ROLE_TABLE;
SELECT * FROM USER_ROLE_MAPPING;